/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entity.Empleado;
import Entity.Usuario;
import dao.empleadoDao;
import daoMysql.empleadoDaoMysql;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adan
 */
public class empleadoInterfaz extends javax.swing.JFrame {

    private Usuario usuario;
    
    public void setUsuario(Usuario usuario){
        this.usuario = usuario;
    }
    
    public Usuario getUsuario(){
        return usuario;
    }
    
    /**
     * Creates new form empleadoInterfaz
     */
    
    private empleadoDao dao = new empleadoDaoMysql();
    
    /**
     * Para agregar formato de la fehca actual del sistema
     */
    public static String Dates(){
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-YYYY");
        return dateFormat.format(date);    
    }
    
    //Inicializa y carga los box de empleados desde la DB
    private void cargarComboBox(){
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        List <Empleado> listaEmpleado = dao.obtenTodos();
        for(int j=0; j<listaEmpleado.size(); j++){
            model.addElement(listaEmpleado.get(j));
        }
        
        empleadoBoxAct.setModel(model);
        empleadoBoxCon.setModel(model);
        empleadoBoxElim.setModel(model);
        
    }
    
    //Vizualiza las consultas de empleado
    private void activaBotones(){
        empleadoBoxCon.setEnabled(false);
        txtConsulta.setEnabled(false);
        grupoBotonConsulta.add(opc_1);
        grupoBotonConsulta.add(opc_2);
        grupoBotonConsulta.add(opc_3);
    }
    
    //Constructor que inicializa todo lo necesario
    public empleadoInterfaz(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        
        this.setLocationRelativeTo(null);
        lblFechaA.setText(Dates());
        
        dao.setUsuario(getUsuario());
        cargarComboBox();
        activaBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotonConsulta = new javax.swing.ButtonGroup();
        menuEmpleado = new javax.swing.JTabbedPane();
        Agregar = new javax.swing.JPanel();
        lblNombreEmpleado = new javax.swing.JLabel();
        lblApellidoP = new javax.swing.JLabel();
        lblSueldoD = new javax.swing.JLabel();
        lblApellidoM1 = new javax.swing.JLabel();
        lblFechaI = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtSueldoD = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        lblFechaA = new javax.swing.JLabel();
        txtFechaIngreso = new com.toedter.calendar.JDateChooser();
        agregarEmpleado = new javax.swing.JButton();
        Mostrar = new javax.swing.JPanel();
        empleadoBoxCon = new javax.swing.JComboBox<>();
        txtConsulta = new javax.swing.JTextField();
        opc_1 = new javax.swing.JRadioButton();
        opc_2 = new javax.swing.JRadioButton();
        opc_3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleado = new javax.swing.JTable();
        btnTodoCon = new javax.swing.JToggleButton();
        btnSeleccionadoCon = new javax.swing.JToggleButton();
        Eliminar = new javax.swing.JPanel();
        empleadoBoxElim = new javax.swing.JComboBox<>();
        btnEliminaEmpleado = new javax.swing.JButton();
        Actualizar = new javax.swing.JPanel();
        empleadoBoxAct = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JToggleButton();
        txtApellidoMAct = new javax.swing.JTextField();
        txtNombreAct = new javax.swing.JTextField();
        txtSueldoAct = new javax.swing.JTextField();
        txtApellidoPAct = new javax.swing.JTextField();
        lblNombreAct = new javax.swing.JLabel();
        lblapellidoPAct = new javax.swing.JLabel();
        lblApellidoMAct = new javax.swing.JLabel();
        lblSueldoAtc = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        cerrarSesion = new javax.swing.JMenu();
        regresar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombreEmpleado.setText("nombre(s)");

        lblApellidoP.setText("Apellido Paterno");

        lblSueldoD.setText("Sueldo Diario");

        lblApellidoM1.setText("Apellido Materno");

        lblFechaI.setText("Fecha de ingreso");

        lblFecha.setText("Fecha Actual");

        lblFechaA.setText("dd-MM-YYYY");

        agregarEmpleado.setText("Agregar");
        agregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AgregarLayout = new javax.swing.GroupLayout(Agregar);
        Agregar.setLayout(AgregarLayout);
        AgregarLayout.setHorizontalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarLayout.createSequentialGroup()
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AgregarLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaA, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFecha, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(AgregarLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agregarEmpleado)
                            .addGroup(AgregarLayout.createSequentialGroup()
                                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblApellidoP)
                                            .addComponent(lblNombreEmpleado))
                                        .addComponent(lblApellidoM1))
                                    .addComponent(lblSueldoD)
                                    .addComponent(lblFechaI))
                                .addGap(82, 82, 82)
                                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSueldoD, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidoM, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellidoP, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        AgregarLayout.setVerticalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFechaA)
                .addGap(21, 21, 21)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNombreEmpleado)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblApellidoP)
                    .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidoM1)
                    .addComponent(txtApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSueldoD)
                    .addComponent(txtSueldoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaI)
                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(agregarEmpleado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblNombreEmpleado.getAccessibleContext().setAccessibleName("lblNombreEmpleado");

        menuEmpleado.addTab("Agregar", Agregar);

        opc_1.setText("nombre");
        opc_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_1ActionPerformed(evt);
            }
        });

        opc_2.setText("Sueldo+");
        opc_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_2ActionPerformed(evt);
            }
        });

        opc_3.setText("Sueldo-");
        opc_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc_3ActionPerformed(evt);
            }
        });

        tablaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Empleado", "Sueldo Diario", "Suendo Diario Integrado", "Fecha de Ingreso", "Antigüedad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Short.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaEmpleado);

        btnTodoCon.setText("todo");
        btnTodoCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodoConActionPerformed(evt);
            }
        });

        btnSeleccionadoCon.setText("Seleccionado");
        btnSeleccionadoCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionadoConActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MostrarLayout = new javax.swing.GroupLayout(Mostrar);
        Mostrar.setLayout(MostrarLayout);
        MostrarLayout.setHorizontalGroup(
            MostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addGroup(MostrarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(MostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empleadoBoxCon, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MostrarLayout.createSequentialGroup()
                                .addComponent(opc_1)
                                .addGap(12, 12, 12)
                                .addComponent(opc_2)
                                .addGap(18, 18, 18)
                                .addComponent(opc_3))
                            .addGroup(MostrarLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnTodoCon, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSeleccionadoCon))
                            .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MostrarLayout.setVerticalGroup(
            MostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostrarLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(empleadoBoxCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(MostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opc_1)
                    .addComponent(opc_2)
                    .addComponent(opc_3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(MostrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTodoCon)
                    .addComponent(btnSeleccionadoCon))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        menuEmpleado.addTab("Mostrar", Mostrar);

        btnEliminaEmpleado.setText("Eliminar");
        btnEliminaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminaEmpleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EliminarLayout = new javax.swing.GroupLayout(Eliminar);
        Eliminar.setLayout(EliminarLayout);
        EliminarLayout.setHorizontalGroup(
            EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empleadoBoxElim, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminaEmpleado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EliminarLayout.setVerticalGroup(
            EliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(empleadoBoxElim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnEliminaEmpleado)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        menuEmpleado.addTab("Eliminar", Eliminar);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        lblNombreAct.setText("Nombre");

        lblapellidoPAct.setText("Apellido Paterno");

        lblApellidoMAct.setText("Apellido Materno");

        lblSueldoAtc.setText("Sueldo Diario");

        javax.swing.GroupLayout ActualizarLayout = new javax.swing.GroupLayout(Actualizar);
        Actualizar.setLayout(ActualizarLayout);
        ActualizarLayout.setHorizontalGroup(
            ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActualizarLayout.createSequentialGroup()
                .addGroup(ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ActualizarLayout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(empleadoBoxAct, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ActualizarLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizar)
                            .addGroup(ActualizarLayout.createSequentialGroup()
                                .addGroup(ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblApellidoMAct, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNombreAct)
                                            .addComponent(lblapellidoPAct)))
                                    .addComponent(lblSueldoAtc))
                                .addGap(12, 12, 12)
                                .addGroup(ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreAct, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                    .addComponent(txtApellidoPAct)
                                    .addComponent(txtApellidoMAct)
                                    .addComponent(txtSueldoAct))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ActualizarLayout.setVerticalGroup(
            ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActualizarLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(empleadoBoxAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreAct))
                .addGap(18, 18, 18)
                .addGroup(ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoPAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblapellidoPAct))
                .addGap(18, 18, 18)
                .addGroup(ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoMAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidoMAct))
                .addGap(18, 18, 18)
                .addGroup(ActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSueldoAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSueldoAtc))
                .addGap(34, 34, 34)
                .addComponent(btnActualizar)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        menuEmpleado.addTab("Actualizar", Actualizar);

        cerrarSesion.setText("Cerrar Sesión");
        cerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionMouseClicked(evt);
            }
        });
        jMenuBar1.add(cerrarSesion);

        regresar.setText("Regresar");
        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });
        jMenuBar1.add(regresar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuEmpleado)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuEmpleado, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * AGREGA LO CAPTURADO EN EL GUI AL OBJETO EMPLEADO PARA MANDARLO A DAOMYSQL E INSERTAR
     */
    private void agregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEmpleadoActionPerformed
        Empleado empleado = new Empleado();
        
        //dao.setUsuario(getUsuario());
        if (txtNombre.getText().equals("") || txtApellidoP.getText().equals("") || txtApellidoM.getText().equals("")
                || txtSueldoD.getText().equals("") || txtFechaIngreso.getDate() == null){
            
            JOptionPane.showMessageDialog(null, "Rellene todos los campos");
            
        }else{
            empleado.setNombre(txtNombre.getText());
            empleado.setApellidoP(txtApellidoP.getText());
            empleado.setApellidoM(txtApellidoM.getText());
            empleado.setSueldo(Double.parseDouble(txtSueldoD.getText()));
            empleado.setFehcaIngreso(txtFechaIngreso.getDate());
            dao.agrega(empleado);
            cargarComboBox();
        }
    }//GEN-LAST:event_agregarEmpleadoActionPerformed

    /**
     * AGREGA LO CAPTURADO EN EL GUI AL OBJETO EMPLEADO PARA MANDARLO A DAOMYSQL Y MODIFICAR
     */
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        Empleado empleado = (Empleado) empleadoBoxAct.getSelectedItem();
        Empleado empleadoActualiza =new Empleado();
        //dao.setUsuario(getUsuario());
        
        empleadoActualiza.setCodigo(empleado.getCodigo());
        empleadoActualiza.setNombre(txtNombreAct.getText());
        empleadoActualiza.setApellidoP(txtApellidoPAct.getText());
        empleadoActualiza.setApellidoM(txtApellidoMAct.getText());
        
        //POR EL PROBLEMA DE CONVERTIR EL TEXT EN DOUBLE SI ES QUE ESTE CAMPO NO SE LLENO
        if("".equals(txtSueldoAct.getText())){
            empleadoActualiza.setSueldo(0.0);
        }else{
            empleadoActualiza.setSueldo(Double.parseDouble(txtSueldoAct.getText()));
        }
        
        dao.Actualiza(empleadoActualiza);
        cargarComboBox();
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * LOS PROXIMOS 3 METODOS SON PARA ABILITAR LOS CAMPOS PARA LAS CONSULTAS
     */
    private void opc_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_1ActionPerformed
        empleadoBoxCon.setEnabled(true);
        txtConsulta.setEnabled(false);
    }//GEN-LAST:event_opc_1ActionPerformed

    private void opc_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_2ActionPerformed
        empleadoBoxCon.setEnabled(false);
        txtConsulta.setEnabled(true);
    }//GEN-LAST:event_opc_2ActionPerformed

    private void opc_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc_3ActionPerformed
        empleadoBoxCon.setEnabled(false);
        txtConsulta.setEnabled(true);
    }//GEN-LAST:event_opc_3ActionPerformed
    
    // PARA ALINEAR LOS DATOS DE LA TABLA
    private void alinear(){
       DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
       tcr.setHorizontalAlignment(SwingConstants.LEFT);
               
       tablaEmpleado.getColumnModel().getColumn(0).setCellRenderer(tcr);
       tablaEmpleado.getColumnModel().getColumn(1).setCellRenderer(tcr);
       tablaEmpleado.getColumnModel().getColumn(2).setCellRenderer(tcr);
       tablaEmpleado.getColumnModel().getColumn(3).setCellRenderer(tcr);
       tablaEmpleado.getColumnModel().getColumn(4).setCellRenderer(tcr);
       tablaEmpleado.getColumnModel().getColumn(5).setCellRenderer(tcr);
    }
    
    //PARA MOSTRAR EL CONTENIDO EN LA TABLA SEGUN EL BOTON SELECCIONADO
    private void agregaEnTabla(List <Empleado> listaEmpleado){
        
        DefaultTableModel modelo = (DefaultTableModel) tablaEmpleado.getModel();
        modelo.setRowCount(0);
        Object []emp=new Object[6];
        for (int i=0; i<listaEmpleado.size(); i++){
            Empleado empleado = listaEmpleado.get(i);
            
            emp[0] = empleado.getCodigo();
            emp[1] = empleado.getApellidoP()+ " " +empleado.getApellidoM()+ " " + empleado.getNombre();
            emp[2] = empleado.getSueldo();
            emp[3] = empleado.getSdi();
            emp[4] = empleado.getFehcaIngreso();
            emp[5] = empleado.getAntiguedad();
            
            modelo.addRow(emp);
        }
        
        alinear();
    }
    /**
     * CONSULTA POR BOTON SELECCIONADO
     */
    private void btnSeleccionadoConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionadoConActionPerformed
        
        dao.setUsuario(getUsuario());
        List <Empleado> listaEmpleado = null;
        
        if(opc_1.isSelected()){
            Empleado empleadoCon = (Empleado) empleadoBoxCon.getSelectedItem();
            int codigo = empleadoCon.getCodigo();
            
            listaEmpleado = dao.obtenEmpleado(codigo);
        }else if (opc_2.isSelected()){
            Double sueldo = Double.parseDouble(txtConsulta.getText());
            listaEmpleado = dao.obtenMayorSueldo(sueldo);
            
        }else if (opc_3.isSelected()){
            Double sueldo = Double.parseDouble(txtConsulta.getText());
            listaEmpleado = dao.obtenMenorSueldo(sueldo);
        }
        
        agregaEnTabla(listaEmpleado);
    }//GEN-LAST:event_btnSeleccionadoConActionPerformed
    
    /**
     * CONSULTA A TODOS LOS EMPLEADOS QUE ESTEN ACTIVOS Y LOS AGREGA A LA TABLA CON UN MODELO
     */
    private void btnTodoConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodoConActionPerformed
        dao.setUsuario(getUsuario());
        List <Empleado> listaEmpleado = dao.obtenTodos();
        agregaEnTabla(listaEmpleado);
    }//GEN-LAST:event_btnTodoConActionPerformed

    /** 
     * Boton Eliminar empleado
     */
    private void btnEliminaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminaEmpleadoActionPerformed
       Empleado empleado = (Empleado) empleadoBoxElim.getSelectedItem();
       //dao.setUsuario(getUsuario());
       if (JOptionPane.showConfirmDialog(rootPane, "¿Seguro que quiere eliminar?","¡ADVERTENCIA!", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            dao.Elimina(empleado);
            cargarComboBox();
        }
    }//GEN-LAST:event_btnEliminaEmpleadoActionPerformed

    private void cerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionMouseClicked
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_cerrarSesionMouseClicked

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
        if(getUsuario().getRole().equals("CONTADOR")){
            menuInterfazCon conInter = new menuInterfazCon(getUsuario());
            conInter.setVisible(true);
            dispose();
        }else{
            menuInterfazGer gerInter = new menuInterfazGer(getUsuario());
            gerInter.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_regresarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Actualizar;
    private javax.swing.JPanel Agregar;
    private javax.swing.JPanel Eliminar;
    private javax.swing.JPanel Mostrar;
    private javax.swing.JButton agregarEmpleado;
    private javax.swing.JToggleButton btnActualizar;
    private javax.swing.JButton btnEliminaEmpleado;
    private javax.swing.JToggleButton btnSeleccionadoCon;
    private javax.swing.JToggleButton btnTodoCon;
    private javax.swing.JMenu cerrarSesion;
    private javax.swing.JComboBox<String> empleadoBoxAct;
    private javax.swing.JComboBox<String> empleadoBoxCon;
    private javax.swing.JComboBox<String> empleadoBoxElim;
    private javax.swing.ButtonGroup grupoBotonConsulta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApellidoM1;
    private javax.swing.JLabel lblApellidoMAct;
    private javax.swing.JLabel lblApellidoP;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaA;
    private javax.swing.JLabel lblFechaI;
    private javax.swing.JLabel lblNombreAct;
    private javax.swing.JLabel lblNombreEmpleado;
    private javax.swing.JLabel lblSueldoAtc;
    private javax.swing.JLabel lblSueldoD;
    private javax.swing.JLabel lblapellidoPAct;
    private javax.swing.JTabbedPane menuEmpleado;
    private javax.swing.JRadioButton opc_1;
    private javax.swing.JRadioButton opc_2;
    private javax.swing.JRadioButton opc_3;
    private javax.swing.JMenu regresar;
    private javax.swing.JTable tablaEmpleado;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoMAct;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtApellidoPAct;
    private javax.swing.JTextField txtConsulta;
    private com.toedter.calendar.JDateChooser txtFechaIngreso;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreAct;
    private javax.swing.JTextField txtSueldoAct;
    private javax.swing.JTextField txtSueldoD;
    // End of variables declaration//GEN-END:variables
}
