/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entity.Usuario;
import Entity.nominaEmpleado;
import dao.nominaEmpleadoDao;
import daoMysql.nominaEmpleadoDaoMysql;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adan
 */
public class menuInterfazEmp extends javax.swing.JFrame {

    private Usuario user;
    
    public Usuario getUsuario(){
        return user;
    }
    
    public void setUsuario(Usuario user){
        this.user = user;
    }
    
    /**
     * Creates new form menuInterfazEmp
     */
    public menuInterfazEmp(Usuario usuario) {
        initComponents();
    
        this.setLocationRelativeTo(null);
        this.user = usuario;
        nombreUsuario();
    }
    
     //Vizualiza en nombre de usuario en el frame
    private void nombreUsuario (){
        String nombreUsuario = getUsuario().getApellidoP() + " " + getUsuario().getApellidoM() + " " + getUsuario().getNombre();
        lblNombreUsuario.setText(nombreUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTodo = new javax.swing.JToggleButton();
        btnFecha = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableNomina = new javax.swing.JTable();
        lblNombreUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTodo.setText("todo");
        btnTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodoActionPerformed(evt);
            }
        });

        btnFecha.setText("Fecha");

        tableNomina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Empleado", "Sueldo Diario", "SDI", "Días Trabajados", "Infonavit", "Cuota IMSS", "Cesantía y Vejez", "Sueldo Neto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Short.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableNomina);

        lblNombreUsuario.setText("jLabel1");

        jMenu2.setText("Cerrar Sesión");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(btnTodo)
                                .addGap(105, 105, 105)
                                .addComponent(btnFecha))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 168, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblNombreUsuario)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTodo)
                    .addComponent(btnFecha))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Para agregar en la tabla 
     private void agregaEnTabla(List <nominaEmpleado> listaNomina){
        
        DefaultTableModel modelo = (DefaultTableModel) tableNomina.getModel();
        modelo.setRowCount(0);
        Object []nom=new Object[9];
        for (int i=0; i<listaNomina.size(); i++){
            nominaEmpleado nomina = listaNomina.get(i);
            
            nom[0] = nomina.getId();
            nom[1] = nomina.getEmpleado().getApellidoP()+ " " +nomina.getEmpleado().getApellidoM()+ " " + nomina.getEmpleado().getNombre();
            nom[2] = nomina.getEmpleado().getSueldo();
            nom[3] = nomina.getEmpleado().getSdi();
            nom[4] = nomina.getDiasTrabajados();
            nom[5] = nomina.getInfonavit();
            nom[6] = nomina.getCuotaImss();
            nom[7] = nomina.getCensantiaVejez();
            nom[8] = nomina.getSueldoNeto();
            
            modelo.addRow(nom);
        }
        
    }
    private void btnTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodoActionPerformed
        nominaEmpleadoDao dao = new nominaEmpleadoDaoMysql();
        
        List <nominaEmpleado> nominaList = dao.obtenNominaEmpleado(getUsuario().getCodigo());
        
        agregaEnTabla(nominaList);
    }//GEN-LAST:event_btnTodoActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFecha;
    private javax.swing.JToggleButton btnTodo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JTable tableNomina;
    // End of variables declaration//GEN-END:variables
}
