/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entity.Empleado;
import Entity.Usuario;
import dao.empleadoDao;
import dao.usuarioDao;
import daoMysql.empleadoDaoMysql;
import daoMysql.usuarioDaoMysql;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Adan
 */
public class usuarioInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form usuarioInterfaz
     */
    private empleadoDao daoE = new empleadoDaoMysql();
    private usuarioDao daoU = new usuarioDaoMysql();
    
    public usuarioInterfaz() {
        initComponents();
        
        grupoBotones.add(Gerente);
        grupoBotones.add(Empleado);
        grupoBotones.add(Contador);
        
        activarBotenes(false);
        cargarComboBox();
    }
    
    //ACTIVAR BOTONES Y DESACTIVAR    
    private void activarBotenes(boolean activo){
            agregaCuota.setEnabled(activo);
            agregaEmpleado.setEnabled(activo);
            agregaNomina.setEnabled(activo);
            
            modificaCuota.setEnabled(activo);
            modificaEmpleado.setEnabled(activo);
            modificaNomina.setEnabled(activo);
            
            eliminaCuota.setEnabled(activo);
            eliminaEmpleado.setEnabled(activo);
            eliminaNomina.setEnabled(activo);
            
            leeCuota.setEnabled(activo);
            leeEmpleado.setEnabled(activo);
            leeNomina.setEnabled(activo);
    }

    //Inicializa y carga los box de empleados desde la DB
    private void cargarComboBox(){
        DefaultComboBoxModel model = new DefaultComboBoxModel();
           
        List <Empleado> listaEmpleado = daoE.obtenTodos();
        for(int j=0; j<listaEmpleado.size(); j++){
            model.addElement(listaEmpleado.get(j));
        }
        
        empleadosBox.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.y
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        agregaNomina = new javax.swing.JRadioButton();
        eliminaNomina = new javax.swing.JRadioButton();
        modificaNomina = new javax.swing.JRadioButton();
        leeNomina = new javax.swing.JRadioButton();
        leeEmpleado = new javax.swing.JRadioButton();
        modificaEmpleado = new javax.swing.JRadioButton();
        eliminaEmpleado = new javax.swing.JRadioButton();
        agregaEmpleado = new javax.swing.JRadioButton();
        leeCuota = new javax.swing.JRadioButton();
        modificaCuota = new javax.swing.JRadioButton();
        eliminaCuota = new javax.swing.JRadioButton();
        agregaCuota = new javax.swing.JRadioButton();
        lblNomina = new javax.swing.JLabel();
        lblEmpleado = new javax.swing.JLabel();
        lblCuota = new javax.swing.JLabel();
        empleadosBox = new javax.swing.JComboBox<>();
        Empleado = new javax.swing.JRadioButton();
        Gerente = new javax.swing.JRadioButton();
        Contador = new javax.swing.JRadioButton();
        txtContrasenaI = new javax.swing.JPasswordField();
        txtContrasenaII = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        agregaNomina.setText("Agrega");

        eliminaNomina.setText("Elimina");

        modificaNomina.setText("Modifica");

        leeNomina.setText("Lee");

        leeEmpleado.setText("Lee");

        modificaEmpleado.setText("Modifica");

        eliminaEmpleado.setText("Elimina");

        agregaEmpleado.setText("Agrega");

        leeCuota.setText("Lee");

        modificaCuota.setText("Modifica");

        eliminaCuota.setText("Elimina");

        agregaCuota.setText("Agrega");

        lblNomina.setText("Nómina:");

        lblEmpleado.setText("Empleado:");

        lblCuota.setText("Cuota");

        Empleado.setText("Empleado");

        Gerente.setText("Gerente");

        Contador.setText("Contador");
        Contador.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ContadorItemStateChanged(evt);
            }
        });

        jLabel1.setText("Ingrese contraseña:");

        jLabel2.setText("Confirme contraseña:");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCuota)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(agregaCuota)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eliminaCuota)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modificaCuota)
                                .addGap(12, 12, 12)
                                .addComponent(leeCuota))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(agregaEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eliminaEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modificaEmpleado)
                                .addGap(12, 12, 12)
                                .addComponent(leeEmpleado))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNomina)
                                .addGap(62, 62, 62)
                                .addComponent(agregaNomina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eliminaNomina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modificaNomina)
                                .addGap(12, 12, 12)
                                .addComponent(leeNomina)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(Empleado)
                                    .addGap(34, 34, 34)
                                    .addComponent(Contador)
                                    .addGap(47, 47, 47)
                                    .addComponent(Gerente))
                                .addComponent(btnAgregar))
                            .addGap(50, 50, 50)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(empleadosBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtContrasenaI)
                            .addComponent(txtContrasenaII, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(111, 111, 111)))
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(empleadosBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrasenaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContrasenaII, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Empleado)
                    .addComponent(Gerente)
                    .addComponent(Contador))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregaNomina)
                    .addComponent(eliminaNomina)
                    .addComponent(modificaNomina)
                    .addComponent(leeNomina)
                    .addComponent(lblNomina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregaEmpleado)
                    .addComponent(eliminaEmpleado)
                    .addComponent(modificaEmpleado)
                    .addComponent(leeEmpleado)
                    .addComponent(lblEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregaCuota)
                    .addComponent(eliminaCuota)
                    .addComponent(modificaCuota)
                    .addComponent(leeCuota)
                    .addComponent(lblCuota))
                .addGap(18, 18, 18)
                .addComponent(btnAgregar)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Eliminar", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Actualizar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContadorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ContadorItemStateChanged
        if (Contador.isSelected()){
            activarBotenes(true);
        }else{
            activarBotenes(false);
        }
    }//GEN-LAST:event_ContadorItemStateChanged

    //AGREGAR USUARIO NUEVO
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String contrasenaI = txtContrasenaI.getText();
        String contrasenaII = txtContrasenaII.getText();
        
        if (contrasenaI.equals(contrasenaII)){
            Usuario usuario = new Usuario();
            Empleado  empleado = (Empleado) empleadosBox.getSelectedItem();
            
            String role="";
            
            //BUSCA QUE OPCION DE ROLE ELIGIO
            if (Contador.isSelected()){
                role = "CONTADOR";
            }else if (Empleado.isSelected()){
                role = "EMPLEADO";
            }else if (Gerente.isSelected()){
                role = "ADMIN";
            }
            
            //CAPTURA LOS DATOS Y LOS MANDA A LA DB
            if (role != ""){
                usuario.setCodigo(empleado.getCodigo());
                usuario.setContrasena(contrasenaI);
                usuario.setRole(role);
                daoU.agrega(usuario);
                                
                //ASIGNAMOS LOS ROLES
                if(role == "CONTADOR"){
                    
                    //Cuota
                    if (agregaCuota.isSelected()){
                        usuario.cuoPriv[0] = "create";
                    }
                    if(leeCuota.isSelected()){
                        usuario.cuoPriv[1] = "read";
                    }
                    if(modificaCuota.isSelected()){
                        usuario.cuoPriv[2] = "update";
                    }
                    if(eliminaCuota.isSelected()){
                        usuario.cuoPriv[3] = "delete";
                    }
                    
                    //Empleado
                    if(agregaEmpleado.isSelected()){
                        usuario.empPriv[0] = "create";
                    }
                    if(leeEmpleado.isSelected()){
                        usuario.empPriv[1] = "read";
                    }
                    if (modificaEmpleado.isSelected()){
                        usuario.empPriv[2] = "update";
                    }
                    if(eliminaEmpleado.isSelected()){
                        usuario.empPriv[3] = "delete";
                    }
                    
                    //Nomina
                    if(agregaNomina.isSelected()){
                        usuario.nomPriv[0] = "create";
                    }
                    if(leeNomina.isSelected()){
                        usuario.nomPriv[1] = "read";
                    }
                    if(modificaNomina.isSelected()){
                        usuario.nomPriv[2] = "update";
                    }
                    if(eliminaNomina.isSelected()){
                        usuario.nomPriv[0] = "delete";
                    }
                    
                    daoU.Actualiza(usuario);
                    
                }else if (role == "EMPLEADO"){
                    //
                    usuario.nomPriv[2] = "read";
                    usuario.empPriv[2] = "read";
                    daoU.Actualiza(usuario);
                }else{
                    //FALTA GERENTE
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "seleccione su Role");
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Verifique la contraseña");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuarioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuarioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuarioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuarioInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuarioInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Contador;
    private javax.swing.JRadioButton Empleado;
    private javax.swing.JRadioButton Gerente;
    private javax.swing.JRadioButton agregaCuota;
    private javax.swing.JRadioButton agregaEmpleado;
    private javax.swing.JRadioButton agregaNomina;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JRadioButton eliminaCuota;
    private javax.swing.JRadioButton eliminaEmpleado;
    private javax.swing.JRadioButton eliminaNomina;
    private javax.swing.JComboBox<String> empleadosBox;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCuota;
    private javax.swing.JLabel lblEmpleado;
    private javax.swing.JLabel lblNomina;
    private javax.swing.JRadioButton leeCuota;
    private javax.swing.JRadioButton leeEmpleado;
    private javax.swing.JRadioButton leeNomina;
    private javax.swing.JRadioButton modificaCuota;
    private javax.swing.JRadioButton modificaEmpleado;
    private javax.swing.JRadioButton modificaNomina;
    private javax.swing.JPasswordField txtContrasenaI;
    private javax.swing.JPasswordField txtContrasenaII;
    // End of variables declaration//GEN-END:variables
}
